apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-deployment
  labels:
    app: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: pgsql
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin1234
            - name: POSTGRES_DB
              value: Contactmanagerdb
      #     volumeMounts:
      #       - name: pgsql-persistent-storage
      #         mountPath: /var/opt/pgsql
      # volumes:
      #   - name: pgsql-persistent-storage
      #     persistentVolumeClaim:
      #       claimName: pgsql-pv-claim
      imagePullSecrets:
        - name: mydockersecret
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql-service
spec:
  selector:
    app: pgsql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32000
  type: NodePort