apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmclean-minimal-api-deployment
  labels:
    app: cmclean-minimal-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cmclean-minimal-api
  template:
    metadata:
      labels:
        app: cmclean-minimal-api
    spec:
      containers:
        - name: cmclean-minimal-api
          image: 6c93f274registry.azurecr.io/cmclean-minimal-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__Default
              valueFrom:
                configMapKeyRef:
                  name: pgsql-connection-configmap
                  key: db-connection-string
            - name: GrpcSettings__ContactGrpcServiceUrl
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: cmclean_grpc_url
            - name: GrpcSettings__AuthorGrpcServiceConsulName
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: cmclean_grpc_consul_name
            - name: RabbitMqConfig__VHostname
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: rabbitmq_config_vhostname
            - name: RabbitMqConfig__Hostname
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: rabbitmq_config_hostname
            - name: RabbitMqConfig__Username
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: rabbitmq_config_username
            - name: RabbitMqConfig__Password
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: rabbitmq_config_password
            - name: RabbitMqConfig__Port
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: rabbitmq_config_port
            - name: RabbitMqConfig__Exchange
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: rabbitmq_config_exchange
            - name: RabbitMqConfig__ExchangeType
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: rabbitmq_config_exchange_type
            - name: AppSettings__ApplicationName
              value: cmclean.MinimalApi
            - name: AppSettings__Instance
              value: "1"
            - name: JaegerSettings__Host
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: jaeger_host
            - name: JaegerSettings__Port
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: jaeger_port
            - name: JaegerSettings__SourceName
              value: "Api"
            - name: JaegerSettings__ServiceName
              value: "cmclean.MinimalApi"
            - name: ExporterSettings__UseExporter
              value: "jaeger"
            - name: Zipkin__Endpoint
              value: "http://zipkin-server-service:9411/api/v2/spans"
            - name: ConsulConfig__Address
              valueFrom:
                configMapKeyRef:
                  name: cmclean-configmap
                  key: consul_address
            - name: ConsulConfig__ServiceAddress
              value: "http://cmclean-minimal-api-service:8001"
            - name: ConsulConfig__ServiceName
              value: "cmcleanMinimalApi"
            - name: ConsulConfig__ServiceId
              value: "cmcleanMinimalApi"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: mydockersecret
---
apiVersion: v1
kind: Service
metadata:
  name: cmclean-minimal-api-service
spec:
  selector:
    app: cmclean-minimal-api
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 80
      nodePort: 31000
  type: NodePort
