apiVersion: v1
kind: ConfigMap
metadata:
  name: db-connection-config-map
  labels:
    app: cmclean
data:
  db-connection-string: "Server=pgsql-service;Database=Contactmanagerdb;Port=5432;User Id=admin;Password=admin1234;"